# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: dxa
author: Jørgen S. Dokken
logo: "docs/logo.png"
copyright: "2023"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 100

# Information about where the book exists on the web
repository:
  url: https://github.com/jorgensd/dxa # Online location of your book
  branch: main

html:
  use_issues_button: true
  use_repository_button: true


bibtex_bibfiles:
  - docs/bibliography.bib


parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

sphinx:
  config:
    html_last_updated_fmt: "%b %d, %Y"
    nb_execution_show_tb: True
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py
    suppress_warnings: ["mystnb.unknown_mime_type"]
    codeautolink_concat_default: True
    intersphinx_mapping:
      basix : ["https://docs.fenicsproject.org/basix/main/python/", null]
      ffcx : ["https://docs.fenicsproject.org/ffcx/main/", null]
      ufl : ["https://docs.fenicsproject.org/ufl/main/", null]
      dolfinx : ["https://docs.fenicsproject.org/dolfinx/main/python/", null]
      scifem: ["http://scientificcomputing.github.io/scifem/", null]
      petsc4py: ["https://petsc.org/release/petsc4py/", null]
      mpi4py: ["https://mpi4py.readthedocs.io/en/stable", null]
      numpy: ["https://numpy.org/doc/stable/", null]
      pyvista: ["https://docs.pyvista.org/", null]
      packaging: ["https://packaging.pypa.io/en/stable/", null]
      checkpoint_schedules: ["https://www.firedrakeproject.org/checkpoint_schedules/", null]
      pyadjoint: ["https://www.dolfin-adjoint.org/en/latest/", null]
      h5py: ["https://docs.h5py.org/en/stable/", null]

  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.intersphinx'
  - 'sphinx_codeautolink'
exclude_patterns: [".pytest_cache/*"]
