name: Build documentation

on:
  push:
    branches:
    - "**"
  workflow_call:
  workflow_dispatch:

env:
  PUBLISH_DIR: ./_build/html
  PYVISTA_TRAME_SERVER_PROXY_PREFIX: "/proxy/"
  PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
  PYVISTA_OFF_SCREEN: false
  PYVISTA_JUPYTER_BACKEND: "html"
  LIBGL_ALWAYS_SOFTWARE: 1
  DISPLAY: ":99.0"

jobs:

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/lab:nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Build docs
        run: jupyter book build -W .

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        # always upload artifact, which can include error messages
        if: always()
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
          retention-days: 2
          if-no-files-found: error

      - name: Show error reports
        if: failure()
        run: |
          find _build/html/reports -type f -print -exec cat {} \;
