name: Build documentation

on:
  push:
    branches:
    - "**"
  workflow_call:
  workflow_dispatch:

env:
  PUBLISH_DIR: ./_build/html

jobs:

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dolfinx:nightly

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Build docs
        run: jupyter book build -W .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.PUBLISH_DIR }}
          name: documentation
