name: Check formatting

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - main
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"

jobs:
  check-code:
    runs-on: ubuntu-22.04

    container: ghcr.io/fenics/dolfinx/dolfinx:nightly

    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v4

      - name: Install code
        run: python3 -m pip install .[dev]

      - name: Flake8 code
        run: python3 -m flake8 -v

      - name: Mypy check
        run: python3 -m mypy -v
