name: Check formatting

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - main
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - main
  workflow_call:

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"

jobs:
  check-code:
    runs-on: ubuntu-latest

    container: ghcr.io/fenics/dolfinx/dolfinx:nightly

    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v4

      - name: Install code
        run: python3 -m pip install .[dev] -U

      - name: ruff Python interface checks
        run: |
          ruff check .
          ruff format --check .
      
      - name: Mypy check
        run: python3 -m mypy .
