name: Test package

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
    
  workflow_dispatch:
  workflow_call:

jobs:
  test-code:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dolfinx:nightly

    steps:
      - uses: actions/checkout@v4

      - name: Install package
        run: python3 -m pip install .[test]

      - name: Run tests
        run: python3 -m pytest -vs .


      - name: Run tests parallel
        run: mpirun -n 2 python3 -m pytest -vs tests/