name: Test package

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
  workflow_call:

jobs:
  test-code:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dolfinx:${{ matrix.label }}
    strategy:
      fail-fast: false
      matrix:
        label: ["stable", "nightly"]

    env:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
      PIP_NO_BUILD_ISOLATION: 0
    steps:
      - uses: actions/checkout@v7

      - name: Install package
        run: python3 -m pip install .[test]

      - name: Run tests
        run: python3 -m pytest -vs .

      - name: Run tests parallel
        run: mpirun -n 2 python3 -m pytest -vs tests/
