name: Test package

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
    
  workflow_dispatch:
  workflow_call:

jobs:
  test-code:
    runs-on: ubuntu:22.04
    container: ghcr.io/fenics/dolfinx/dolfinx:nightly

    steps:
      - uses: actions/checkout@v3

      - name: Install package
        run: python3 -m pip install .[test]

      - name: Run tests
        run: python3 -m pytest
